# Copy from FF2-Official too
# Use the new container-based infrastructure
sudo: false

# Install some apt packages needed for spcomp
addons:
    apt_packages:
        - lib32stdc++6

# Set the build environment
env:
    - SMVERSION=1.7 # Legacy
    - SMVERSION=1.8 # Legacy
    - SMVERSION=1.9 # Stable

# And compile!
install:
    - wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
    - tar -xzf $(cat sourcemod-latest-linux)
before_script:
    - cd addons/sourcemod/scripting/
    - wget "https://raw.githubusercontent.com/asherkin/TF2Items/master/pawn/tf2items.inc" -O include/tf2items.inc
    - wget "http://www.doctormckay.com/download/scripting/include/morecolors.inc" -O include/morecolors.inc
    - wget "https://raw.githubusercontent.com/asherkin/SteamTools/master/plugin/steamtools.inc" -O include/steamtools.inc
    - wget "https://bitbucket.org/GoD_Tony/updater/raw/default/include/updater.inc" -O include/updater.inc
    - wget "https://raw.githubusercontent.com/Flyflo/SM-Goomba-Stomp/master/addons/sourcemod/scripting/include/goomba.inc" -O include/goomba.inc
    - wget "https://raw.githubusercontent.com/Phil25/RTD/master/scripting/include/rtd2.inc" -O include/rtd2.inc
    - wget "https://forums.alliedmods.net/attachment.php?attachmentid=116849&d=1377667508" -O include/tf2attributes.inc

    - chmod +x spcomp
    - mkdir compiled
script: ./compile.sh freak_fortress_2.sp

# Notifications
notifications:
    email: false
